package com.MTG.AppLock.util

import com.MTG.AppLock.R
import com.MTG.AppLock.data.sqllite.AppLockHelper
import com.MTG.AppLock.model.ThemeModel
import com.MTG.pinlock.ThemeConfig

object ThemeUtils {
    const val TYPE_PATTERN = 1
    const val TYPE_PIN = 2
    const val TYPE_WALLPAPER = 3

    fun initThemeDefault(appLockHelper: AppLockHelper, initDefault: Boolean) {
        // pattern
        if (initDefault) {
            appLockHelper.addTheme(ThemeModel(typeTheme = TYPE_PATTERN))
        }
        appLockHelper.addTheme(ThemeModel(typeTheme = TYPE_PATTERN, backgroundResId = R.drawable.background_1, thumbnailResId = R.drawable.type_pattern_1, selectedResId = R.drawable.ic_theme_1_selected, unselectedResId = R.drawable.ic_theme_1_unselected, lineColorResId = R.color.color_line_theme_1, themeConfig = ThemeConfig(mutableListOf(1, 2, 4, 9))))//
        appLockHelper.addTheme(ThemeModel(typeTheme = TYPE_PATTERN, backgroundResId = R.drawable.background_2, thumbnailResId = R.drawable.type_pattern_2, selectedResId = R.drawable.ic_theme_2_selected, unselectedResId = R.drawable.ic_theme_2_unselected, lineColorResId = R.color.color_line_theme_2, themeConfig = ThemeConfig(mutableListOf(1, 2, 6, 9))))//
        var selectedResList = mutableListOf<Int>()
        selectedResList.add(R.drawable.ic_theme_3_selected_1)
        selectedResList.add(R.drawable.ic_theme_3_selected_2)
        selectedResList.add(R.drawable.ic_theme_3_selected_3)
        selectedResList.add(R.drawable.ic_theme_3_selected_4)
        selectedResList.add(R.drawable.ic_theme_3_selected_5)
        selectedResList.add(R.drawable.ic_theme_3_selected_6)
        selectedResList.add(R.drawable.ic_theme_3_selected_7)
        selectedResList.add(R.drawable.ic_theme_3_selected_8)
        selectedResList.add(R.drawable.ic_theme_3_selected_9)
        var unselectedResList = mutableListOf<Int>()
        unselectedResList.add(R.drawable.ic_theme_3_unselected_1)
        unselectedResList.add(R.drawable.ic_theme_3_unselected_2)
        unselectedResList.add(R.drawable.ic_theme_3_unselected_3)
        unselectedResList.add(R.drawable.ic_theme_3_unselected_4)
        unselectedResList.add(R.drawable.ic_theme_3_unselected_5)
        unselectedResList.add(R.drawable.ic_theme_3_unselected_6)
        unselectedResList.add(R.drawable.ic_theme_3_unselected_7)
        unselectedResList.add(R.drawable.ic_theme_3_unselected_8)
        unselectedResList.add(R.drawable.ic_theme_3_unselected_9)
        appLockHelper.addTheme(ThemeModel(typeTheme = TYPE_PATTERN, backgroundResId = R.drawable.background_3, thumbnailResId = R.drawable.type_pattern_3, selectedResIdList = selectedResList, unselectedResIdList = unselectedResList, lineColorResId = R.color.color_line_theme_3, themeConfig = ThemeConfig(mutableListOf(1, 2, 6, 9))))
        appLockHelper.addTheme(ThemeModel(typeTheme = TYPE_PATTERN, backgroundResId = R.drawable.background_4, thumbnailResId = R.drawable.type_pattern_4, selectedResId = R.drawable.ic_theme_4_selected, unselectedResId = R.drawable.ic_theme_4_unselected, lineColorResId = R.color.color_line_theme_4, themeConfig = ThemeConfig(mutableListOf(1, 2, 6, 9))))
        appLockHelper.addTheme(ThemeModel(typeTheme = TYPE_PATTERN, backgroundResId = R.drawable.background_5, thumbnailResId = R.drawable.type_pattern_5, selectedResId = R.drawable.ic_theme_5_selected, unselectedResId = R.drawable.ic_theme_5_unselected, lineColorResId = R.color.color_line_theme_5, themeConfig = ThemeConfig(mutableListOf(1, 2, 6, 9))))
        selectedResList = mutableListOf()
        selectedResList.add(R.drawable.ic_theme_6_selected_1)
        selectedResList.add(R.drawable.ic_theme_6_selected_2)
        selectedResList.add(R.drawable.ic_theme_6_selected_3)
        selectedResList.add(R.drawable.ic_theme_6_selected_4)
        selectedResList.add(R.drawable.ic_theme_6_selected_5)
        selectedResList.add(R.drawable.ic_theme_6_selected_6)
        selectedResList.add(R.drawable.ic_theme_6_selected_7)
        selectedResList.add(R.drawable.ic_theme_6_selected_8)
        selectedResList.add(R.drawable.ic_theme_6_selected_9)
        unselectedResList = mutableListOf()
        unselectedResList.add(R.drawable.ic_theme_6_unselected)
        appLockHelper.addTheme(ThemeModel(typeTheme = TYPE_PATTERN, backgroundResId = R.drawable.background_6, thumbnailResId = R.drawable.type_pattern_6, selectedResIdList = selectedResList, unselectedResIdList = unselectedResList, lineColorResId = R.color.color_line_theme_6, themeConfig = ThemeConfig(mutableListOf(1, 2, 6, 9))))
        selectedResList = mutableListOf()
        selectedResList.add(R.drawable.ic_theme_7_selected_1)
        selectedResList.add(R.drawable.ic_theme_7_selected_2)
        selectedResList.add(R.drawable.ic_theme_7_selected_3)
        selectedResList.add(R.drawable.ic_theme_7_selected_4)
        selectedResList.add(R.drawable.ic_theme_7_selected_5)
        selectedResList.add(R.drawable.ic_theme_7_selected_6)
        selectedResList.add(R.drawable.ic_theme_7_selected_7)
        selectedResList.add(R.drawable.ic_theme_7_selected_8)
        selectedResList.add(R.drawable.ic_theme_7_selected_9)
        unselectedResList = mutableListOf()
        unselectedResList.add(R.drawable.ic_theme_7_unselected_1)
        unselectedResList.add(R.drawable.ic_theme_7_unselected_2)
        unselectedResList.add(R.drawable.ic_theme_7_unselected_3)
        unselectedResList.add(R.drawable.ic_theme_7_unselected_4)
        unselectedResList.add(R.drawable.ic_theme_7_unselected_5)
        unselectedResList.add(R.drawable.ic_theme_7_unselected_6)
        unselectedResList.add(R.drawable.ic_theme_7_unselected_7)
        unselectedResList.add(R.drawable.ic_theme_7_unselected_8)
        unselectedResList.add(R.drawable.ic_theme_7_unselected_9)
        appLockHelper.addTheme(ThemeModel(typeTheme = TYPE_PATTERN, backgroundResId = R.drawable.background_7, thumbnailResId = R.drawable.type_pattern_7, selectedResIdList = selectedResList, unselectedResIdList = unselectedResList, lineColorResId = R.color.color_line_theme_7, themeConfig = ThemeConfig(mutableListOf(1, 2, 6, 9))))
        selectedResList = mutableListOf()
        selectedResList.add(R.drawable.ic_theme_8_selected_1)
        selectedResList.add(R.drawable.ic_theme_8_selected_2)
        selectedResList.add(R.drawable.ic_theme_8_selected_3)
        selectedResList.add(R.drawable.ic_theme_8_selected_4)
        selectedResList.add(R.drawable.ic_theme_8_selected_5)
        selectedResList.add(R.drawable.ic_theme_8_selected_6)
        selectedResList.add(R.drawable.ic_theme_8_selected_7)
        selectedResList.add(R.drawable.ic_theme_8_selected_8)
        selectedResList.add(R.drawable.ic_theme_8_selected_9)
        unselectedResList = mutableListOf()
        unselectedResList.add(R.drawable.ic_theme_8_unselected)
        appLockHelper.addTheme(ThemeModel(typeTheme = TYPE_PATTERN, backgroundResId = R.drawable.background_8, thumbnailResId = R.drawable.type_pattern_8, selectedResIdList = selectedResList, unselectedResIdList = unselectedResList, lineColorResId = R.color.color_line_theme_8, themeConfig = ThemeConfig(mutableListOf(1, 2, 6, 9))))
        // pin
        var resPinList = mutableListOf<Int>()
        resPinList.add(R.drawable.ic_pin1_number0)
        resPinList.add(R.drawable.ic_pin1_number1)
        resPinList.add(R.drawable.ic_pin1_number2)
        resPinList.add(R.drawable.ic_pin1_number3)
        resPinList.add(R.drawable.ic_pin1_number4)
        resPinList.add(R.drawable.ic_pin1_number5)
        resPinList.add(R.drawable.ic_pin1_number6)
        resPinList.add(R.drawable.ic_pin1_number7)
        resPinList.add(R.drawable.ic_pin1_number8)
        resPinList.add(R.drawable.ic_pin1_number9)
        resPinList.add(R.drawable.ic_pin1_numberx)
        appLockHelper.addTheme(ThemeModel(typeTheme = TYPE_PIN, backgroundResId = R.drawable.background2_1, thumbnailResId = R.drawable.type_pin_1, textMsgColorResId = R.color.color_message_theme_1, buttonResList = resPinList, selectorCheckboxColorResId = R.drawable.selector_checkbox_pin_1, isDeletePadding = false, themeConfig = ThemeConfig(4, true, mutableListOf())))

        resPinList = mutableListOf()
        resPinList.add(R.drawable.ic_pin2_number0)
        resPinList.add(R.drawable.ic_pin2_number1)
        resPinList.add(R.drawable.ic_pin2_number2)
        resPinList.add(R.drawable.ic_pin2_number3)
        resPinList.add(R.drawable.ic_pin2_number4)
        resPinList.add(R.drawable.ic_pin2_number5)
        resPinList.add(R.drawable.ic_pin2_number6)
        resPinList.add(R.drawable.ic_pin2_number7)
        resPinList.add(R.drawable.ic_pin2_number8)
        resPinList.add(R.drawable.ic_pin2_number9)
        resPinList.add(R.drawable.ic_pin2_numberx)
        val themeModel = ThemeModel(typeTheme = TYPE_PIN, backgroundResId = R.drawable.background2_2, thumbnailResId = R.drawable.type_pin_2, buttonResList = resPinList, selectorCheckboxColorResId = R.drawable.selector_checkbox_pin_2, isDeletePadding = true, isNumberPadding = false, deletePadding = 0, themeConfig = ThemeConfig(4, true, mutableListOf()))
        appLockHelper.addTheme(themeModel)

        //
        resPinList = mutableListOf()
        resPinList.add(R.drawable.ic_pin3_number0)
        resPinList.add(R.drawable.ic_pin3_number1)
        resPinList.add(R.drawable.ic_pin3_number2)
        resPinList.add(R.drawable.ic_pin3_number3)
        resPinList.add(R.drawable.ic_pin3_number4)
        resPinList.add(R.drawable.ic_pin3_number5)
        resPinList.add(R.drawable.ic_pin3_number6)
        resPinList.add(R.drawable.ic_pin3_number7)
        resPinList.add(R.drawable.ic_pin3_number8)
        resPinList.add(R.drawable.ic_pin3_number9)
        resPinList.add(R.drawable.ic_pin3_numberx)
        appLockHelper.addTheme(ThemeModel(typeTheme = TYPE_PIN, backgroundResId = R.drawable.background2_3, thumbnailResId = R.drawable.type_pin_3, buttonResList = resPinList, selectorCheckboxColorResId = R.drawable.selector_checkbox_pin_3, isDeletePadding = true, deletePadding = 14, themeConfig = ThemeConfig(4, true, mutableListOf())))

        resPinList = mutableListOf()
        resPinList.add(R.drawable.ic_pin4_number0)
        resPinList.add(R.drawable.ic_pin4_number1)
        resPinList.add(R.drawable.ic_pin4_number2)
        resPinList.add(R.drawable.ic_pin4_number3)
        resPinList.add(R.drawable.ic_pin4_number4)
        resPinList.add(R.drawable.ic_pin4_number5)
        resPinList.add(R.drawable.ic_pin4_number6)
        resPinList.add(R.drawable.ic_pin4_number7)
        resPinList.add(R.drawable.ic_pin4_number8)
        resPinList.add(R.drawable.ic_pin4_number9)
        resPinList.add(R.drawable.ic_pin4_numberx)
        appLockHelper.addTheme(ThemeModel(typeTheme = TYPE_PIN, backgroundResId = R.drawable.background2_4, thumbnailResId = R.drawable.type_pin_4, buttonResList = resPinList, selectorCheckboxColorResId = R.drawable.selector_checkbox_pin_4, isDeletePadding = true, isNumberPadding = false, themeConfig = ThemeConfig(4, true, mutableListOf())))

        resPinList = mutableListOf()
        resPinList.add(R.drawable.ic_pin5_number0)
        resPinList.add(R.drawable.ic_pin5_number1)
        resPinList.add(R.drawable.ic_pin5_number2)
        resPinList.add(R.drawable.ic_pin5_number3)
        resPinList.add(R.drawable.ic_pin5_number4)
        resPinList.add(R.drawable.ic_pin5_number5)
        resPinList.add(R.drawable.ic_pin5_number6)
        resPinList.add(R.drawable.ic_pin5_number7)
        resPinList.add(R.drawable.ic_pin5_number8)
        resPinList.add(R.drawable.ic_pin5_number9)
        resPinList.add(R.drawable.ic_pin5_numberx)
        appLockHelper.addTheme(ThemeModel(typeTheme = TYPE_PIN, backgroundResId = R.drawable.background2_5, thumbnailResId = R.drawable.type_pin_5, buttonResList = resPinList, selectorCheckboxColorResId = R.drawable.selector_checkbox_pin_5, isDeletePadding = true, isNumberPadding = false, deletePadding = 0, themeConfig = ThemeConfig(4, true, mutableListOf())))

        resPinList = mutableListOf()
        resPinList.add(R.drawable.ic_pin6_number0)
        resPinList.add(R.drawable.ic_pin6_number1)
        resPinList.add(R.drawable.ic_pin6_number2)
        resPinList.add(R.drawable.ic_pin6_number3)
        resPinList.add(R.drawable.ic_pin6_number4)
        resPinList.add(R.drawable.ic_pin6_number5)
        resPinList.add(R.drawable.ic_pin6_number6)
        resPinList.add(R.drawable.ic_pin6_number7)
        resPinList.add(R.drawable.ic_pin6_number8)
        resPinList.add(R.drawable.ic_pin6_number9)
        resPinList.add(R.drawable.ic_pin6_numberx)
        appLockHelper.addTheme(ThemeModel(typeTheme = TYPE_PIN, backgroundResId = R.drawable.background2_6, thumbnailResId = R.drawable.type_pin_6, buttonResList = resPinList, selectorCheckboxColorResId = R.drawable.selector_checkbox_pin_6, isDeletePadding = true, deletePadding = 14, themeConfig = ThemeConfig(4, true, mutableListOf())))

        resPinList = mutableListOf()
        resPinList.add(R.drawable.ic_pin7_number0)
        resPinList.add(R.drawable.ic_pin7_number1)
        resPinList.add(R.drawable.ic_pin7_number2)
        resPinList.add(R.drawable.ic_pin7_number3)
        resPinList.add(R.drawable.ic_pin7_number4)
        resPinList.add(R.drawable.ic_pin7_number5)
        resPinList.add(R.drawable.ic_pin7_number6)
        resPinList.add(R.drawable.ic_pin7_number7)
        resPinList.add(R.drawable.ic_pin7_number8)
        resPinList.add(R.drawable.ic_pin7_number9)
        resPinList.add(R.drawable.ic_pin7_numberx)
        appLockHelper.addTheme(ThemeModel(typeTheme = TYPE_PIN, backgroundResId = R.drawable.background2_7, thumbnailResId = R.drawable.type_pin_7, buttonResList = resPinList, selectorCheckboxColorResId = R.drawable.selector_checkbox_pin_7, isDeletePadding = true, deletePadding = 22, themeConfig = ThemeConfig(4, true, mutableListOf())))

        resPinList = mutableListOf()
        resPinList.add(R.drawable.ic_pin8_number0)
        resPinList.add(R.drawable.ic_pin8_number1)
        resPinList.add(R.drawable.ic_pin8_number2)
        resPinList.add(R.drawable.ic_pin8_number3)
        resPinList.add(R.drawable.ic_pin8_number4)
        resPinList.add(R.drawable.ic_pin8_number5)
        resPinList.add(R.drawable.ic_pin8_number6)
        resPinList.add(R.drawable.ic_pin8_number7)
        resPinList.add(R.drawable.ic_pin8_number8)
        resPinList.add(R.drawable.ic_pin8_number9)
        resPinList.add(R.drawable.ic_pin8_numberx)
        appLockHelper.addTheme(ThemeModel(typeTheme = TYPE_PIN, backgroundResId = R.drawable.background2_8, thumbnailResId = R.drawable.type_pin_8, buttonResList = resPinList, selectorCheckboxColorResId = R.drawable.selector_checkbox_pin_8, isDeletePadding = false, isNumberPadding = false, deletePadding = 12, themeConfig = ThemeConfig(4, true, mutableListOf())))

        // wallpaper
        appLockHelper.addTheme(ThemeModel(typeTheme = TYPE_WALLPAPER, backgroundResId = R.drawable.background_1, thumbnailResId = R.drawable.background_1))
        appLockHelper.addTheme(ThemeModel(typeTheme = TYPE_WALLPAPER, backgroundResId = R.drawable.background_2, thumbnailResId = R.drawable.background_2))
        appLockHelper.addTheme(ThemeModel(typeTheme = TYPE_WALLPAPER, backgroundResId = R.drawable.background_3, thumbnailResId = R.drawable.background_3))
        appLockHelper.addTheme(ThemeModel(typeTheme = TYPE_WALLPAPER, backgroundResId = R.drawable.background_4, thumbnailResId = R.drawable.background_4))
        appLockHelper.addTheme(ThemeModel(typeTheme = TYPE_WALLPAPER, backgroundResId = R.drawable.background_5, thumbnailResId = R.drawable.background_5))
        appLockHelper.addTheme(ThemeModel(typeTheme = TYPE_WALLPAPER, backgroundResId = R.drawable.background_7, thumbnailResId = R.drawable.background_7))
        appLockHelper.addTheme(ThemeModel(typeTheme = TYPE_WALLPAPER, backgroundResId = R.drawable.background_8, thumbnailResId = R.drawable.background_8))
        appLockHelper.addTheme(ThemeModel(typeTheme = TYPE_WALLPAPER, backgroundResId = R.drawable.background2_2, thumbnailResId = R.drawable.background2_2))
        appLockHelper.addTheme(ThemeModel(typeTheme = TYPE_WALLPAPER, backgroundResId = R.drawable.background2_3, thumbnailResId = R.drawable.background2_3))
        appLockHelper.addTheme(ThemeModel(typeTheme = TYPE_WALLPAPER, backgroundResId = R.drawable.background2_4, thumbnailResId = R.drawable.background2_4))
        appLockHelper.addTheme(ThemeModel(typeTheme = TYPE_WALLPAPER, backgroundResId = R.drawable.background2_5, thumbnailResId = R.drawable.background2_5))
        appLockHelper.addTheme(ThemeModel(typeTheme = TYPE_WALLPAPER, backgroundResId = R.drawable.background2_6, thumbnailResId = R.drawable.background2_6))
        appLockHelper.addTheme(ThemeModel(typeTheme = TYPE_WALLPAPER, backgroundResId = R.drawable.background2_7, thumbnailResId = R.drawable.background2_7))
        appLockHelper.addTheme(ThemeModel(typeTheme = TYPE_WALLPAPER, backgroundResId = R.drawable.background2_8, thumbnailResId = R.drawable.background2_8))
    }
}